SET default_with_oids = false;

CREATE TABLE planeigenaar (
    id integer NOT NULL,
    naam character varying(255),
    code character varying(255)
);

CREATE SEQUENCE planeigenaar_id_seq
    INCREMENT BY 1
    NO MAXVALUE
    NO MINVALUE
    CACHE 1;

ALTER SEQUENCE planeigenaar_id_seq OWNED BY planeigenaar.id;

SELECT pg_catalog.setval('planeigenaar_id_seq', 498, true);

ALTER TABLE planeigenaar ALTER COLUMN id SET DEFAULT nextval('planeigenaar_id_seq'::regclass);

INSERT INTO planeigenaar (id, naam, code) VALUES (1, 'Amsterdam', '0363');
INSERT INTO planeigenaar (id, naam, code) VALUES (2, 'Weesp', '0457');
INSERT INTO planeigenaar (id, naam, code) VALUES (3, 'Blaricum', '0376');
INSERT INTO planeigenaar (id, naam, code) VALUES (4, 'Ouder-Amstel', '0437');
INSERT INTO planeigenaar (id, naam, code) VALUES (5, 'Amstelveen', '0362');
INSERT INTO planeigenaar (id, naam, code) VALUES (6, 'Eemnes', '0317');
INSERT INTO planeigenaar (id, naam, code) VALUES (7, 'Laren', '0417');
INSERT INTO planeigenaar (id, naam, code) VALUES (8, 'Uithoorn', '0451');
INSERT INTO planeigenaar (id, naam, code) VALUES (9, 'Abcoude', '0305');
INSERT INTO planeigenaar (id, naam, code) VALUES (10, 'Bunschoten', '0313');
INSERT INTO planeigenaar (id, naam, code) VALUES (11, 'Hilversum', '0402');
INSERT INTO planeigenaar (id, naam, code) VALUES (12, 'De Ronde Venen', '0736');
INSERT INTO planeigenaar (id, naam, code) VALUES (13, 'Nieuwkoop', '0569');
INSERT INTO planeigenaar (id, naam, code) VALUES (14, 'Baarn', '0308');
INSERT INTO planeigenaar (id, naam, code) VALUES (15, 'Wijdemeren', '1696');
INSERT INTO planeigenaar (id, naam, code) VALUES (16, 'Loenen', '0329');
INSERT INTO planeigenaar (id, naam, code) VALUES (17, 'Nijkerk', '0267');
INSERT INTO planeigenaar (id, naam, code) VALUES (18, 'Soest', '0342');
INSERT INTO planeigenaar (id, naam, code) VALUES (19, 'Barneveld', '0203');
INSERT INTO planeigenaar (id, naam, code) VALUES (20, 'Breukelen', '0311');
INSERT INTO planeigenaar (id, naam, code) VALUES (21, 'Maarssen', '0333');
INSERT INTO planeigenaar (id, naam, code) VALUES (22, 'Amersfoort', '0307');
INSERT INTO planeigenaar (id, naam, code) VALUES (23, 'Leusden', '0327');
INSERT INTO planeigenaar (id, naam, code) VALUES (24, 'Utrecht', '0344');
INSERT INTO planeigenaar (id, naam, code) VALUES (25, 'De Bilt', '0310');
INSERT INTO planeigenaar (id, naam, code) VALUES (26, 'Renswoude', '0339');
INSERT INTO planeigenaar (id, naam, code) VALUES (27, 'Bodegraven', '0497');
INSERT INTO planeigenaar (id, naam, code) VALUES (28, 'Woudenberg', '0351');
INSERT INTO planeigenaar (id, naam, code) VALUES (29, 'Woerden', '0632');
INSERT INTO planeigenaar (id, naam, code) VALUES (30, 'Ede', '0228');
INSERT INTO planeigenaar (id, naam, code) VALUES (31, 'Scherpenzeel', '0279');
INSERT INTO planeigenaar (id, naam, code) VALUES (32, 'Utrechtse Heuvelrug', '1581');
INSERT INTO planeigenaar (id, naam, code) VALUES (33, 'Zeist', '0355');
INSERT INTO planeigenaar (id, naam, code) VALUES (34, 'Montfoort', '0335');
INSERT INTO planeigenaar (id, naam, code) VALUES (35, 'Oudewater', '0589');
INSERT INTO planeigenaar (id, naam, code) VALUES (36, 'Bunnik', '0312');
INSERT INTO planeigenaar (id, naam, code) VALUES (37, 'Reeuwijk', '0595');
INSERT INTO planeigenaar (id, naam, code) VALUES (38, 'Houten', '0321');
INSERT INTO planeigenaar (id, naam, code) VALUES (39, 'Veenendaal', '0345');
INSERT INTO planeigenaar (id, naam, code) VALUES (40, 'Nieuwegein', '0356');
INSERT INTO planeigenaar (id, naam, code) VALUES (41, 'IJsselstein', '0353');
INSERT INTO planeigenaar (id, naam, code) VALUES (42, 'Wijk bij Duurstede', '0352');
INSERT INTO planeigenaar (id, naam, code) VALUES (43, 'Vlist', '0623');
INSERT INTO planeigenaar (id, naam, code) VALUES (44, 'Rhenen', '0340');
INSERT INTO planeigenaar (id, naam, code) VALUES (45, 'Lopik', '0331');
INSERT INTO planeigenaar (id, naam, code) VALUES (46, 'Wageningen', '0289');
INSERT INTO planeigenaar (id, naam, code) VALUES (47, 'Vianen', '0620');
INSERT INTO planeigenaar (id, naam, code) VALUES (48, 'Culemborg', '0216');
INSERT INTO planeigenaar (id, naam, code) VALUES (49, 'Schoonhoven', '0608');
INSERT INTO planeigenaar (id, naam, code) VALUES (50, 'Liesveld', '0694');
INSERT INTO planeigenaar (id, naam, code) VALUES (51, 'Neder-Betuwe', '1740');
INSERT INTO planeigenaar (id, naam, code) VALUES (52, 'Leerdam', '0545');
INSERT INTO planeigenaar (id, naam, code) VALUES (53, 'Buren', '0214');
INSERT INTO planeigenaar (id, naam, code) VALUES (54, 'Zederik', '0707');
INSERT INTO planeigenaar (id, naam, code) VALUES (55, 'Arnhem', '0202');
INSERT INTO planeigenaar (id, naam, code) VALUES (56, 'Appingedam', '0003');
INSERT INTO planeigenaar (id, naam, code) VALUES (57, 'Bedum', '0005');
INSERT INTO planeigenaar (id, naam, code) VALUES (58, 'Bellingwedde', '0007');
INSERT INTO planeigenaar (id, naam, code) VALUES (59, 'Ten Boer', '0009');
INSERT INTO planeigenaar (id, naam, code) VALUES (60, 'Delfzijl', '0010');
INSERT INTO planeigenaar (id, naam, code) VALUES (61, 'Groningen', '0014');
INSERT INTO planeigenaar (id, naam, code) VALUES (62, 'Grootegast', '0015');
INSERT INTO planeigenaar (id, naam, code) VALUES (63, 'Haren', '0017');
INSERT INTO planeigenaar (id, naam, code) VALUES (64, 'Hoogezand-Sappemeer', '0018');
INSERT INTO planeigenaar (id, naam, code) VALUES (65, 'Leek', '0022');
INSERT INTO planeigenaar (id, naam, code) VALUES (66, 'Loppersum', '0024');
INSERT INTO planeigenaar (id, naam, code) VALUES (67, 'Marum', '0025');
INSERT INTO planeigenaar (id, naam, code) VALUES (68, 'Almere', '0034');
INSERT INTO planeigenaar (id, naam, code) VALUES (69, 'Stadskanaal', '0037');
INSERT INTO planeigenaar (id, naam, code) VALUES (70, 'Scheemda', '0039');
INSERT INTO planeigenaar (id, naam, code) VALUES (71, 'Slochteren', '0040');
INSERT INTO planeigenaar (id, naam, code) VALUES (72, 'Veendam', '0047');
INSERT INTO planeigenaar (id, naam, code) VALUES (73, 'Vlagtwedde', '0048');
INSERT INTO planeigenaar (id, naam, code) VALUES (74, 'Zeewolde', '0050');
INSERT INTO planeigenaar (id, naam, code) VALUES (75, 'Skarsterl?n', '0051');
INSERT INTO planeigenaar (id, naam, code) VALUES (76, 'Winschoten', '0052');
INSERT INTO planeigenaar (id, naam, code) VALUES (77, 'Winsum', '0053');
INSERT INTO planeigenaar (id, naam, code) VALUES (78, 'Boarnsterhim', '0055');
INSERT INTO planeigenaar (id, naam, code) VALUES (79, 'Zuidhorn', '0056');
INSERT INTO planeigenaar (id, naam, code) VALUES (80, 'Dongeradeel', '0058');
INSERT INTO planeigenaar (id, naam, code) VALUES (81, 'Achtkarspelen', '0059');
INSERT INTO planeigenaar (id, naam, code) VALUES (82, 'Ameland', '0060');
INSERT INTO planeigenaar (id, naam, code) VALUES (83, 'het Bildt', '0063');
INSERT INTO planeigenaar (id, naam, code) VALUES (84, 'Bolsward', '0064');
INSERT INTO planeigenaar (id, naam, code) VALUES (85, 'Dantumadeel', '0065');
INSERT INTO planeigenaar (id, naam, code) VALUES (86, 'Franekeradeel', '0070');
INSERT INTO planeigenaar (id, naam, code) VALUES (87, 'Harlingen', '0072');
INSERT INTO planeigenaar (id, naam, code) VALUES (88, 'Heerenveen', '0074');
INSERT INTO planeigenaar (id, naam, code) VALUES (89, 'Kollumerland en Nieuwkruisland', '0079');
INSERT INTO planeigenaar (id, naam, code) VALUES (90, 'Leeuwarden', '0080');
INSERT INTO planeigenaar (id, naam, code) VALUES (91, 'Leeuwarderadeel', '0081');
INSERT INTO planeigenaar (id, naam, code) VALUES (92, 'Lemsterland', '0082');
INSERT INTO planeigenaar (id, naam, code) VALUES (93, 'Menaldumadeel', '0083');
INSERT INTO planeigenaar (id, naam, code) VALUES (94, 'Ooststellingwerf', '0085');
INSERT INTO planeigenaar (id, naam, code) VALUES (95, 'Opsterland', '0086');
INSERT INTO planeigenaar (id, naam, code) VALUES (96, 'Schiermonnikoog', '0088');
INSERT INTO planeigenaar (id, naam, code) VALUES (97, 'Smallingerland', '0090');
INSERT INTO planeigenaar (id, naam, code) VALUES (98, 'Sneek', '0091');
INSERT INTO planeigenaar (id, naam, code) VALUES (99, 'Terschelling', '0093');
INSERT INTO planeigenaar (id, naam, code) VALUES (100, 'Vlieland', '0096');
INSERT INTO planeigenaar (id, naam, code) VALUES (101, 'Weststellingwerf', '0098');
INSERT INTO planeigenaar (id, naam, code) VALUES (102, 'Nijefurd', '0104');
INSERT INTO planeigenaar (id, naam, code) VALUES (103, 'Assen', '0106');
INSERT INTO planeigenaar (id, naam, code) VALUES (104, 'Coevorden', '0109');
INSERT INTO planeigenaar (id, naam, code) VALUES (105, 'Emmen', '0114');
INSERT INTO planeigenaar (id, naam, code) VALUES (106, 'Hoogeveen', '0118');
INSERT INTO planeigenaar (id, naam, code) VALUES (107, 'Meppel', '0119');
INSERT INTO planeigenaar (id, naam, code) VALUES (108, 'Littenseradiel', '0140');
INSERT INTO planeigenaar (id, naam, code) VALUES (109, 'Almelo', '0141');
INSERT INTO planeigenaar (id, naam, code) VALUES (110, 'Borne', '0147');
INSERT INTO planeigenaar (id, naam, code) VALUES (111, 'Dalfsen', '0148');
INSERT INTO planeigenaar (id, naam, code) VALUES (112, 'Deventer', '0150');
INSERT INTO planeigenaar (id, naam, code) VALUES (113, 'Enschede', '0153');
INSERT INTO planeigenaar (id, naam, code) VALUES (114, 'Haaksbergen', '0158');
INSERT INTO planeigenaar (id, naam, code) VALUES (115, 'Hardenberg', '0160');
INSERT INTO planeigenaar (id, naam, code) VALUES (116, 'Hellendoorn', '0163');
INSERT INTO planeigenaar (id, naam, code) VALUES (117, 'Hengelo', '0164');
INSERT INTO planeigenaar (id, naam, code) VALUES (118, 'Kampen', '0166');
INSERT INTO planeigenaar (id, naam, code) VALUES (119, 'Losser', '0168');
INSERT INTO planeigenaar (id, naam, code) VALUES (120, 'Noordoostpolder', '0171');
INSERT INTO planeigenaar (id, naam, code) VALUES (121, 'Oldenzaal', '0173');
INSERT INTO planeigenaar (id, naam, code) VALUES (122, 'Ommen', '0175');
INSERT INTO planeigenaar (id, naam, code) VALUES (123, 'Raalte', '0177');
INSERT INTO planeigenaar (id, naam, code) VALUES (124, 'Staphorst', '0180');
INSERT INTO planeigenaar (id, naam, code) VALUES (125, 'Tubbergen', '0183');
INSERT INTO planeigenaar (id, naam, code) VALUES (126, 'Urk', '0184');
INSERT INTO planeigenaar (id, naam, code) VALUES (127, 'Wierden', '0189');
INSERT INTO planeigenaar (id, naam, code) VALUES (128, 'Zwolle', '0193');
INSERT INTO planeigenaar (id, naam, code) VALUES (129, 'Rijnwaarden', '0196');
INSERT INTO planeigenaar (id, naam, code) VALUES (130, 'Aalten', '0197');
INSERT INTO planeigenaar (id, naam, code) VALUES (131, 'Apeldoorn', '0200');
INSERT INTO planeigenaar (id, naam, code) VALUES (132, 'Arnhem', '0202');
INSERT INTO planeigenaar (id, naam, code) VALUES (133, 'Barneveld', '0203');
INSERT INTO planeigenaar (id, naam, code) VALUES (134, 'Beuningen', '0209');
INSERT INTO planeigenaar (id, naam, code) VALUES (135, 'Brummen', '0213');
INSERT INTO planeigenaar (id, naam, code) VALUES (136, 'Buren', '0214');
INSERT INTO planeigenaar (id, naam, code) VALUES (137, 'Culemborg', '0216');
INSERT INTO planeigenaar (id, naam, code) VALUES (138, 'Doesburg', '0221');
INSERT INTO planeigenaar (id, naam, code) VALUES (139, 'Doetinchem', '0222');
INSERT INTO planeigenaar (id, naam, code) VALUES (140, 'Druten', '0225');
INSERT INTO planeigenaar (id, naam, code) VALUES (141, 'Duiven', '0226');
INSERT INTO planeigenaar (id, naam, code) VALUES (142, 'Ede', '0228');
INSERT INTO planeigenaar (id, naam, code) VALUES (143, 'Elburg', '0230');
INSERT INTO planeigenaar (id, naam, code) VALUES (144, 'Epe', '0232');
INSERT INTO planeigenaar (id, naam, code) VALUES (145, 'Ermelo', '0233');
INSERT INTO planeigenaar (id, naam, code) VALUES (146, 'Geldermalsen', '0236');
INSERT INTO planeigenaar (id, naam, code) VALUES (147, 'Groesbeek', '0241');
INSERT INTO planeigenaar (id, naam, code) VALUES (148, 'Harderwijk', '0243');
INSERT INTO planeigenaar (id, naam, code) VALUES (149, 'Hattem', '0244');
INSERT INTO planeigenaar (id, naam, code) VALUES (150, 'Heerde', '0246');
INSERT INTO planeigenaar (id, naam, code) VALUES (151, 'Heumen', '0252');
INSERT INTO planeigenaar (id, naam, code) VALUES (152, 'Lochem', '0262');
INSERT INTO planeigenaar (id, naam, code) VALUES (153, 'Maasdriel', '0263');
INSERT INTO planeigenaar (id, naam, code) VALUES (154, 'Millingen aan de Rijn', '0265');
INSERT INTO planeigenaar (id, naam, code) VALUES (155, 'Nijkerk', '0267');
INSERT INTO planeigenaar (id, naam, code) VALUES (156, 'Nijmegen', '0268');
INSERT INTO planeigenaar (id, naam, code) VALUES (157, 'Oldebroek', '0269');
INSERT INTO planeigenaar (id, naam, code) VALUES (158, 'Putten', '0273');
INSERT INTO planeigenaar (id, naam, code) VALUES (159, 'Renkum', '0274');
INSERT INTO planeigenaar (id, naam, code) VALUES (160, 'Rheden', '0275');
INSERT INTO planeigenaar (id, naam, code) VALUES (161, 'Rozendaal', '0277');
INSERT INTO planeigenaar (id, naam, code) VALUES (162, 'Scherpenzeel', '0279');
INSERT INTO planeigenaar (id, naam, code) VALUES (163, 'Tiel', '0281');
INSERT INTO planeigenaar (id, naam, code) VALUES (164, 'Ubbergen', '0282');
INSERT INTO planeigenaar (id, naam, code) VALUES (165, 'Voorst', '0285');
INSERT INTO planeigenaar (id, naam, code) VALUES (166, 'Wageningen', '0289');
INSERT INTO planeigenaar (id, naam, code) VALUES (167, 'Westervoort', '0293');
INSERT INTO planeigenaar (id, naam, code) VALUES (168, 'Winterswijk', '0294');
INSERT INTO planeigenaar (id, naam, code) VALUES (169, 'Wijchen', '0296');
INSERT INTO planeigenaar (id, naam, code) VALUES (170, 'Zaltbommel', '0297');
INSERT INTO planeigenaar (id, naam, code) VALUES (171, 'Zevenaar', '0299');
INSERT INTO planeigenaar (id, naam, code) VALUES (172, 'Zutphen', '0301');
INSERT INTO planeigenaar (id, naam, code) VALUES (173, 'Nunspeet', '0302');
INSERT INTO planeigenaar (id, naam, code) VALUES (174, 'Dronten', '0303');
INSERT INTO planeigenaar (id, naam, code) VALUES (175, 'Neerijnen', '0304');
INSERT INTO planeigenaar (id, naam, code) VALUES (176, 'Abcoude', '0305');
INSERT INTO planeigenaar (id, naam, code) VALUES (177, 'Amersfoort', '0307');
INSERT INTO planeigenaar (id, naam, code) VALUES (178, 'Baarn', '0308');
INSERT INTO planeigenaar (id, naam, code) VALUES (179, 'De Bilt', '0310');
INSERT INTO planeigenaar (id, naam, code) VALUES (180, 'Breukelen', '0311');
INSERT INTO planeigenaar (id, naam, code) VALUES (181, 'Bunnik', '0312');
INSERT INTO planeigenaar (id, naam, code) VALUES (182, 'Bunschoten', '0313');
INSERT INTO planeigenaar (id, naam, code) VALUES (183, 'Eemnes', '0317');
INSERT INTO planeigenaar (id, naam, code) VALUES (184, 'Houten', '0321');
INSERT INTO planeigenaar (id, naam, code) VALUES (185, 'Leusden', '0327');
INSERT INTO planeigenaar (id, naam, code) VALUES (186, 'Loenen', '0329');
INSERT INTO planeigenaar (id, naam, code) VALUES (187, 'Lopik', '0331');
INSERT INTO planeigenaar (id, naam, code) VALUES (188, 'Maarssen', '0333');
INSERT INTO planeigenaar (id, naam, code) VALUES (189, 'Montfoort', '0335');
INSERT INTO planeigenaar (id, naam, code) VALUES (190, 'Renswoude', '0339');
INSERT INTO planeigenaar (id, naam, code) VALUES (191, 'Rhenen', '0340');
INSERT INTO planeigenaar (id, naam, code) VALUES (192, 'Soest', '0342');
INSERT INTO planeigenaar (id, naam, code) VALUES (193, 'Utrecht', '0344');
INSERT INTO planeigenaar (id, naam, code) VALUES (194, 'Veenendaal', '0345');
INSERT INTO planeigenaar (id, naam, code) VALUES (195, 'Woudenberg', '0351');
INSERT INTO planeigenaar (id, naam, code) VALUES (196, 'Wijk bij Duurstede', '0352');
INSERT INTO planeigenaar (id, naam, code) VALUES (197, 'IJsselstein', '0353');
INSERT INTO planeigenaar (id, naam, code) VALUES (198, 'Zeist', '0355');
INSERT INTO planeigenaar (id, naam, code) VALUES (199, 'Nieuwegein', '0356');
INSERT INTO planeigenaar (id, naam, code) VALUES (200, 'Aalsmeer', '0358');
INSERT INTO planeigenaar (id, naam, code) VALUES (201, 'Alkmaar', '0361');
INSERT INTO planeigenaar (id, naam, code) VALUES (202, 'Amstelveen', '0362');
INSERT INTO planeigenaar (id, naam, code) VALUES (203, 'Amsterdam', '0363');
INSERT INTO planeigenaar (id, naam, code) VALUES (204, 'Andijk', '0364');
INSERT INTO planeigenaar (id, naam, code) VALUES (205, 'Graft-De Rijp', '0365');
INSERT INTO planeigenaar (id, naam, code) VALUES (206, 'Anna Paulowna', '0366');
INSERT INTO planeigenaar (id, naam, code) VALUES (207, 'Beemster', '0370');
INSERT INTO planeigenaar (id, naam, code) VALUES (208, 'Bennebroek', '0372');
INSERT INTO planeigenaar (id, naam, code) VALUES (209, 'Bergen (NH.)', '0373');
INSERT INTO planeigenaar (id, naam, code) VALUES (210, 'Beverwijk', '0375');
INSERT INTO planeigenaar (id, naam, code) VALUES (211, 'Blaricum', '0376');
INSERT INTO planeigenaar (id, naam, code) VALUES (212, 'Bloemendaal', '0377');
INSERT INTO planeigenaar (id, naam, code) VALUES (213, 'Bussum', '0381');
INSERT INTO planeigenaar (id, naam, code) VALUES (214, 'Castricum', '0383');
INSERT INTO planeigenaar (id, naam, code) VALUES (215, 'Diemen', '0384');
INSERT INTO planeigenaar (id, naam, code) VALUES (216, 'Edam-Volendam', '0385');
INSERT INTO planeigenaar (id, naam, code) VALUES (217, 'Enkhuizen', '0388');
INSERT INTO planeigenaar (id, naam, code) VALUES (218, 'Haarlem', '0392');
INSERT INTO planeigenaar (id, naam, code) VALUES (219, 'Haarlemmerliede en Spaarnwoude', '0393');
INSERT INTO planeigenaar (id, naam, code) VALUES (220, 'Haarlemmermeer', '0394');
INSERT INTO planeigenaar (id, naam, code) VALUES (221, 'Harenkarspel', '0395');
INSERT INTO planeigenaar (id, naam, code) VALUES (222, 'Heemskerk', '0396');
INSERT INTO planeigenaar (id, naam, code) VALUES (223, 'Heemstede', '0397');
INSERT INTO planeigenaar (id, naam, code) VALUES (224, 'Heerhugowaard', '0398');
INSERT INTO planeigenaar (id, naam, code) VALUES (225, 'Heiloo', '0399');
INSERT INTO planeigenaar (id, naam, code) VALUES (226, 'Den Helder', '0400');
INSERT INTO planeigenaar (id, naam, code) VALUES (227, 'Hilversum', '0402');
INSERT INTO planeigenaar (id, naam, code) VALUES (228, 'Hoorn', '0405');
INSERT INTO planeigenaar (id, naam, code) VALUES (229, 'Huizen', '0406');
INSERT INTO planeigenaar (id, naam, code) VALUES (230, 'Niedorp', '0412');
INSERT INTO planeigenaar (id, naam, code) VALUES (231, 'Landsmeer', '0415');
INSERT INTO planeigenaar (id, naam, code) VALUES (232, 'Langedijk', '0416');
INSERT INTO planeigenaar (id, naam, code) VALUES (233, 'Laren', '0417');
INSERT INTO planeigenaar (id, naam, code) VALUES (234, 'Medemblik', '0420');
INSERT INTO planeigenaar (id, naam, code) VALUES (235, 'Muiden', '0424');
INSERT INTO planeigenaar (id, naam, code) VALUES (236, 'Naarden', '0425');
INSERT INTO planeigenaar (id, naam, code) VALUES (237, 'Oostzaan', '0431');
INSERT INTO planeigenaar (id, naam, code) VALUES (238, 'Opmeer', '0432');
INSERT INTO planeigenaar (id, naam, code) VALUES (239, 'Ouder-Amstel', '0437');
INSERT INTO planeigenaar (id, naam, code) VALUES (240, 'Purmerend', '0439');
INSERT INTO planeigenaar (id, naam, code) VALUES (241, 'Schagen', '0441');
INSERT INTO planeigenaar (id, naam, code) VALUES (242, 'Texel', '0448');
INSERT INTO planeigenaar (id, naam, code) VALUES (243, 'Uitgeest', '0450');
INSERT INTO planeigenaar (id, naam, code) VALUES (244, 'Uithoorn', '0451');
INSERT INTO planeigenaar (id, naam, code) VALUES (245, 'Velsen', '0453');
INSERT INTO planeigenaar (id, naam, code) VALUES (246, 'Weesp', '0457');
INSERT INTO planeigenaar (id, naam, code) VALUES (247, 'Schermer', '0458');
INSERT INTO planeigenaar (id, naam, code) VALUES (248, 'Wervershoof', '0459');
INSERT INTO planeigenaar (id, naam, code) VALUES (249, 'Wieringen', '0462');
INSERT INTO planeigenaar (id, naam, code) VALUES (250, 'Wieringermeer', '0463');
INSERT INTO planeigenaar (id, naam, code) VALUES (251, 'Zandvoort', '0473');
INSERT INTO planeigenaar (id, naam, code) VALUES (252, 'Zijpe', '0476');
INSERT INTO planeigenaar (id, naam, code) VALUES (253, 'Zeevang', '0478');
INSERT INTO planeigenaar (id, naam, code) VALUES (254, 'Zaanstad', '0479');
INSERT INTO planeigenaar (id, naam, code) VALUES (255, 'Alblasserdam', '0482');
INSERT INTO planeigenaar (id, naam, code) VALUES (256, 'Alkemade', '0483');
INSERT INTO planeigenaar (id, naam, code) VALUES (257, 'Alphen aan den Rijn', '0484');
INSERT INTO planeigenaar (id, naam, code) VALUES (258, 'Barendrecht', '0489');
INSERT INTO planeigenaar (id, naam, code) VALUES (259, 'Bergambacht', '0491');
INSERT INTO planeigenaar (id, naam, code) VALUES (260, 'Bodegraven', '0497');
INSERT INTO planeigenaar (id, naam, code) VALUES (261, 'Drechterland', '0498');
INSERT INTO planeigenaar (id, naam, code) VALUES (262, 'Boskoop', '0499');
INSERT INTO planeigenaar (id, naam, code) VALUES (263, 'Brielle', '0501');
INSERT INTO planeigenaar (id, naam, code) VALUES (264, 'Capelle aan den IJssel', '0502');
INSERT INTO planeigenaar (id, naam, code) VALUES (265, 'Delft', '0503');
INSERT INTO planeigenaar (id, naam, code) VALUES (266, 'Dirksland', '0504');
INSERT INTO planeigenaar (id, naam, code) VALUES (267, 'Dordrecht', '0505');
INSERT INTO planeigenaar (id, naam, code) VALUES (268, 'Goedereede', '0511');
INSERT INTO planeigenaar (id, naam, code) VALUES (269, 'Gorinchem', '0512');
INSERT INTO planeigenaar (id, naam, code) VALUES (270, 'Gouda', '0513');
INSERT INTO planeigenaar (id, naam, code) VALUES (271, '''s-Gravenhage', '0518');
INSERT INTO planeigenaar (id, naam, code) VALUES (272, 'Hardinxveld-Giessendam', '0523');
INSERT INTO planeigenaar (id, naam, code) VALUES (273, 'Hellevoetsluis', '0530');
INSERT INTO planeigenaar (id, naam, code) VALUES (274, 'Hendrik-Ido-Ambacht', '0531');
INSERT INTO planeigenaar (id, naam, code) VALUES (275, 'Stede Broec', '0532');
INSERT INTO planeigenaar (id, naam, code) VALUES (276, 'Hillegom', '0534');
INSERT INTO planeigenaar (id, naam, code) VALUES (277, 'Katwijk', '0537');
INSERT INTO planeigenaar (id, naam, code) VALUES (278, 'Krimpen aan den IJssel', '0542');
INSERT INTO planeigenaar (id, naam, code) VALUES (279, 'Leerdam', '0545');
INSERT INTO planeigenaar (id, naam, code) VALUES (280, 'Leiden', '0546');
INSERT INTO planeigenaar (id, naam, code) VALUES (281, 'Leiderdorp', '0547');
INSERT INTO planeigenaar (id, naam, code) VALUES (282, 'Lisse', '0553');
INSERT INTO planeigenaar (id, naam, code) VALUES (283, 'Maassluis', '0556');
INSERT INTO planeigenaar (id, naam, code) VALUES (284, 'Middelharnis', '0559');
INSERT INTO planeigenaar (id, naam, code) VALUES (285, 'Moordrecht', '0563');
INSERT INTO planeigenaar (id, naam, code) VALUES (286, 'Nieuwerkerk aan den IJssel', '0567');
INSERT INTO planeigenaar (id, naam, code) VALUES (287, 'Bernisse', '0568');
INSERT INTO planeigenaar (id, naam, code) VALUES (288, 'Nieuwkoop', '0569');
INSERT INTO planeigenaar (id, naam, code) VALUES (289, 'Nieuw-Lekkerland', '0571');
INSERT INTO planeigenaar (id, naam, code) VALUES (290, 'Noordwijk', '0575');
INSERT INTO planeigenaar (id, naam, code) VALUES (291, 'Noordwijkerhout', '0576');
INSERT INTO planeigenaar (id, naam, code) VALUES (292, 'Oegstgeest', '0579');
INSERT INTO planeigenaar (id, naam, code) VALUES (293, 'Oostflakkee', '0580');
INSERT INTO planeigenaar (id, naam, code) VALUES (294, 'Oud-Beijerland', '0584');
INSERT INTO planeigenaar (id, naam, code) VALUES (295, 'Binnenmaas', '0585');
INSERT INTO planeigenaar (id, naam, code) VALUES (296, 'Korendijk', '0588');
INSERT INTO planeigenaar (id, naam, code) VALUES (297, 'Oudewater', '0589');
INSERT INTO planeigenaar (id, naam, code) VALUES (298, 'Papendrecht', '0590');
INSERT INTO planeigenaar (id, naam, code) VALUES (299, 'Reeuwijk', '0595');
INSERT INTO planeigenaar (id, naam, code) VALUES (300, 'Ridderkerk', '0597');
INSERT INTO planeigenaar (id, naam, code) VALUES (301, 'Rotterdam', '0599');
INSERT INTO planeigenaar (id, naam, code) VALUES (302, 'Rozenburg', '0600');
INSERT INTO planeigenaar (id, naam, code) VALUES (303, 'Rijswijk', '0603');
INSERT INTO planeigenaar (id, naam, code) VALUES (304, 'Schiedam', '0606');
INSERT INTO planeigenaar (id, naam, code) VALUES (305, 'Schoonhoven', '0608');
INSERT INTO planeigenaar (id, naam, code) VALUES (306, 'Sliedrecht', '0610');
INSERT INTO planeigenaar (id, naam, code) VALUES (307, 'Cromstrijen', '0611');
INSERT INTO planeigenaar (id, naam, code) VALUES (308, 'Spijkenisse', '0612');
INSERT INTO planeigenaar (id, naam, code) VALUES (309, 'Albrandswaard', '0613');
INSERT INTO planeigenaar (id, naam, code) VALUES (310, 'Westvoorne', '0614');
INSERT INTO planeigenaar (id, naam, code) VALUES (311, 'Strijen', '0617');
INSERT INTO planeigenaar (id, naam, code) VALUES (312, 'Vianen', '0620');
INSERT INTO planeigenaar (id, naam, code) VALUES (313, 'Vlaardingen', '0622');
INSERT INTO planeigenaar (id, naam, code) VALUES (314, 'Vlist', '0623');
INSERT INTO planeigenaar (id, naam, code) VALUES (315, 'Voorschoten', '0626');
INSERT INTO planeigenaar (id, naam, code) VALUES (316, 'Waddinxveen', '0627');
INSERT INTO planeigenaar (id, naam, code) VALUES (317, 'Wassenaar', '0629');
INSERT INTO planeigenaar (id, naam, code) VALUES (318, 'Woerden', '0632');
INSERT INTO planeigenaar (id, naam, code) VALUES (319, 'Zoetermeer', '0637');
INSERT INTO planeigenaar (id, naam, code) VALUES (320, 'Zoeterwoude', '0638');
INSERT INTO planeigenaar (id, naam, code) VALUES (321, 'Zwijndrecht', '0642');
INSERT INTO planeigenaar (id, naam, code) VALUES (322, 'Nederlek', '0643');
INSERT INTO planeigenaar (id, naam, code) VALUES (323, 'Ouderkerk', '0644');
INSERT INTO planeigenaar (id, naam, code) VALUES (324, 'Jacobswoude', '0645');
INSERT INTO planeigenaar (id, naam, code) VALUES (325, 'Gaasterl?n-Sleat', '0653');
INSERT INTO planeigenaar (id, naam, code) VALUES (326, 'Borsele', '0654');
INSERT INTO planeigenaar (id, naam, code) VALUES (327, 'Goes', '0664');
INSERT INTO planeigenaar (id, naam, code) VALUES (328, 'West Maas en Waal', '0668');
INSERT INTO planeigenaar (id, naam, code) VALUES (329, 'Hulst', '0677');
INSERT INTO planeigenaar (id, naam, code) VALUES (330, 'Kapelle', '0678');
INSERT INTO planeigenaar (id, naam, code) VALUES (331, 'Wymbritseradiel', '0683');
INSERT INTO planeigenaar (id, naam, code) VALUES (332, 'Middelburg', '0687');
INSERT INTO planeigenaar (id, naam, code) VALUES (333, 'Giessenlanden', '0689');
INSERT INTO planeigenaar (id, naam, code) VALUES (334, 'Graafstroom', '0693');
INSERT INTO planeigenaar (id, naam, code) VALUES (335, 'Liesveld', '0694');
INSERT INTO planeigenaar (id, naam, code) VALUES (336, 'Reimerswaal', '0703');
INSERT INTO planeigenaar (id, naam, code) VALUES (337, 'Zederik', '0707');
INSERT INTO planeigenaar (id, naam, code) VALUES (338, 'W?nseradiel', '0710');
INSERT INTO planeigenaar (id, naam, code) VALUES (339, 'Terneuzen', '0715');
INSERT INTO planeigenaar (id, naam, code) VALUES (340, 'Tholen', '0716');
INSERT INTO planeigenaar (id, naam, code) VALUES (341, 'Veere', '0717');
INSERT INTO planeigenaar (id, naam, code) VALUES (342, 'Vlissingen', '0718');
INSERT INTO planeigenaar (id, naam, code) VALUES (343, 'Lingewaal', '0733');
INSERT INTO planeigenaar (id, naam, code) VALUES (344, 'De Ronde Venen', '0736');
INSERT INTO planeigenaar (id, naam, code) VALUES (345, 'Tytsjerksteradiel', '0737');
INSERT INTO planeigenaar (id, naam, code) VALUES (346, 'Aalburg', '0738');
INSERT INTO planeigenaar (id, naam, code) VALUES (347, 'Asten', '0743');
INSERT INTO planeigenaar (id, naam, code) VALUES (348, 'Baarle-Nassau', '0744');
INSERT INTO planeigenaar (id, naam, code) VALUES (349, 'Bergen op Zoom', '0748');
INSERT INTO planeigenaar (id, naam, code) VALUES (350, 'Best', '0753');
INSERT INTO planeigenaar (id, naam, code) VALUES (351, 'Boekel', '0755');
INSERT INTO planeigenaar (id, naam, code) VALUES (352, 'Boxmeer', '0756');
INSERT INTO planeigenaar (id, naam, code) VALUES (353, 'Boxtel', '0757');
INSERT INTO planeigenaar (id, naam, code) VALUES (354, 'Breda', '0758');
INSERT INTO planeigenaar (id, naam, code) VALUES (355, 'Deurne', '0762');
INSERT INTO planeigenaar (id, naam, code) VALUES (356, 'Pekela', '0765');
INSERT INTO planeigenaar (id, naam, code) VALUES (357, 'Dongen', '0766');
INSERT INTO planeigenaar (id, naam, code) VALUES (358, 'Eersel', '0770');
INSERT INTO planeigenaar (id, naam, code) VALUES (359, 'Eindhoven', '0772');
INSERT INTO planeigenaar (id, naam, code) VALUES (360, 'Etten-Leur', '0777');
INSERT INTO planeigenaar (id, naam, code) VALUES (361, 'Geertruidenberg', '0779');
INSERT INTO planeigenaar (id, naam, code) VALUES (362, 'Gilze en Rijen', '0784');
INSERT INTO planeigenaar (id, naam, code) VALUES (363, 'Goirle', '0785');
INSERT INTO planeigenaar (id, naam, code) VALUES (364, 'Grave', '0786');
INSERT INTO planeigenaar (id, naam, code) VALUES (365, 'Haaren', '0788');
INSERT INTO planeigenaar (id, naam, code) VALUES (366, 'Helmond', '0794');
INSERT INTO planeigenaar (id, naam, code) VALUES (367, '''s-Hertogenbosch', '0796');
INSERT INTO planeigenaar (id, naam, code) VALUES (368, 'Heusden', '0797');
INSERT INTO planeigenaar (id, naam, code) VALUES (369, 'Hilvarenbeek', '0798');
INSERT INTO planeigenaar (id, naam, code) VALUES (370, 'Lith', '0808');
INSERT INTO planeigenaar (id, naam, code) VALUES (371, 'Loon op Zand', '0809');
INSERT INTO planeigenaar (id, naam, code) VALUES (372, 'Mill en Sint Hubert', '0815');
INSERT INTO planeigenaar (id, naam, code) VALUES (373, 'Nuenen, Gerwen en Nederwetten', '0820');
INSERT INTO planeigenaar (id, naam, code) VALUES (374, 'Oirschot', '0823');
INSERT INTO planeigenaar (id, naam, code) VALUES (375, 'Oisterwijk', '0824');
INSERT INTO planeigenaar (id, naam, code) VALUES (376, 'Oosterhout', '0826');
INSERT INTO planeigenaar (id, naam, code) VALUES (377, 'Oss', '0828');
INSERT INTO planeigenaar (id, naam, code) VALUES (378, 'Rucphen', '0840');
INSERT INTO planeigenaar (id, naam, code) VALUES (379, 'Schijndel', '0844');
INSERT INTO planeigenaar (id, naam, code) VALUES (380, 'Sint-Michielsgestel', '0845');
INSERT INTO planeigenaar (id, naam, code) VALUES (381, 'Sint-Oedenrode', '0846');
INSERT INTO planeigenaar (id, naam, code) VALUES (382, 'Someren', '0847');
INSERT INTO planeigenaar (id, naam, code) VALUES (383, 'Son en Breugel', '0848');
INSERT INTO planeigenaar (id, naam, code) VALUES (384, 'Steenbergen', '0851');
INSERT INTO planeigenaar (id, naam, code) VALUES (385, 'Waterland', '0852');
INSERT INTO planeigenaar (id, naam, code) VALUES (386, 'Tilburg', '0855');
INSERT INTO planeigenaar (id, naam, code) VALUES (387, 'Uden', '0856');
INSERT INTO planeigenaar (id, naam, code) VALUES (388, 'Valkenswaard', '0858');
INSERT INTO planeigenaar (id, naam, code) VALUES (389, 'Veghel', '0860');
INSERT INTO planeigenaar (id, naam, code) VALUES (390, 'Veldhoven', '0861');
INSERT INTO planeigenaar (id, naam, code) VALUES (391, 'Vught', '0865');
INSERT INTO planeigenaar (id, naam, code) VALUES (392, 'Waalre', '0866');
INSERT INTO planeigenaar (id, naam, code) VALUES (393, 'Waalwijk', '0867');
INSERT INTO planeigenaar (id, naam, code) VALUES (394, 'Werkendam', '0870');
INSERT INTO planeigenaar (id, naam, code) VALUES (395, 'Woensdrecht', '0873');
INSERT INTO planeigenaar (id, naam, code) VALUES (396, 'Woudrichem', '0874');
INSERT INTO planeigenaar (id, naam, code) VALUES (397, 'Zundert', '0879');
INSERT INTO planeigenaar (id, naam, code) VALUES (398, 'Wormerland', '0880');
INSERT INTO planeigenaar (id, naam, code) VALUES (399, 'Onderbanken', '0881');
INSERT INTO planeigenaar (id, naam, code) VALUES (400, 'Landgraaf', '0882');
INSERT INTO planeigenaar (id, naam, code) VALUES (401, 'Arcen en Velden', '0885');
INSERT INTO planeigenaar (id, naam, code) VALUES (402, 'Beek', '0888');
INSERT INTO planeigenaar (id, naam, code) VALUES (403, 'Beesel', '0889');
INSERT INTO planeigenaar (id, naam, code) VALUES (404, 'Bergen (L.)', '0893');
INSERT INTO planeigenaar (id, naam, code) VALUES (405, 'Brunssum', '0899');
INSERT INTO planeigenaar (id, naam, code) VALUES (406, 'Eijsden', '0905');
INSERT INTO planeigenaar (id, naam, code) VALUES (407, 'Gennep', '0907');
INSERT INTO planeigenaar (id, naam, code) VALUES (408, 'Heerlen', '0917');
INSERT INTO planeigenaar (id, naam, code) VALUES (409, 'Helden', '0918');
INSERT INTO planeigenaar (id, naam, code) VALUES (410, 'Kerkrade', '0928');
INSERT INTO planeigenaar (id, naam, code) VALUES (411, 'Kessel', '0929');
INSERT INTO planeigenaar (id, naam, code) VALUES (412, 'Maasbree', '0934');
INSERT INTO planeigenaar (id, naam, code) VALUES (413, 'Maastricht', '0935');
INSERT INTO planeigenaar (id, naam, code) VALUES (414, 'Margraten', '0936');
INSERT INTO planeigenaar (id, naam, code) VALUES (415, 'Meerssen', '0938');
INSERT INTO planeigenaar (id, naam, code) VALUES (416, 'Meijel', '0941');
INSERT INTO planeigenaar (id, naam, code) VALUES (417, 'Mook en Middelaar', '0944');
INSERT INTO planeigenaar (id, naam, code) VALUES (418, 'Nederweert', '0946');
INSERT INTO planeigenaar (id, naam, code) VALUES (419, 'Nuth', '0951');
INSERT INTO planeigenaar (id, naam, code) VALUES (420, 'Roermond', '0957');
INSERT INTO planeigenaar (id, naam, code) VALUES (421, 'Schinnen', '0962');
INSERT INTO planeigenaar (id, naam, code) VALUES (422, 'Sevenum', '0964');
INSERT INTO planeigenaar (id, naam, code) VALUES (423, 'Simpelveld', '0965');
INSERT INTO planeigenaar (id, naam, code) VALUES (424, 'Stein', '0971');
INSERT INTO planeigenaar (id, naam, code) VALUES (425, 'Vaals', '0981');
INSERT INTO planeigenaar (id, naam, code) VALUES (426, 'Venlo', '0983');
INSERT INTO planeigenaar (id, naam, code) VALUES (427, 'Venray', '0984');
INSERT INTO planeigenaar (id, naam, code) VALUES (428, 'Voerendaal', '0986');
INSERT INTO planeigenaar (id, naam, code) VALUES (429, 'Weert', '0988');
INSERT INTO planeigenaar (id, naam, code) VALUES (430, 'Meerlo-Wanssum', '0993');
INSERT INTO planeigenaar (id, naam, code) VALUES (431, 'Valkenburg aan de Geul', '0994');
INSERT INTO planeigenaar (id, naam, code) VALUES (432, 'Lelystad', '0995');
INSERT INTO planeigenaar (id, naam, code) VALUES (433, 'Horst aan de Maas', '1507');
INSERT INTO planeigenaar (id, naam, code) VALUES (434, 'Oude IJsselstreek', '1509');
INSERT INTO planeigenaar (id, naam, code) VALUES (435, 'Teylingen', '1525');
INSERT INTO planeigenaar (id, naam, code) VALUES (436, 'Utrechtse Heuvelrug', '1581');
INSERT INTO planeigenaar (id, naam, code) VALUES (437, 'Oost Gelre', '1586');
INSERT INTO planeigenaar (id, naam, code) VALUES (438, 'Koggenland', '1598');
INSERT INTO planeigenaar (id, naam, code) VALUES (439, 'Lansingerland', '1621');
INSERT INTO planeigenaar (id, naam, code) VALUES (440, 'Leudal', '1640');
INSERT INTO planeigenaar (id, naam, code) VALUES (441, 'Maasgouw', '1641');
INSERT INTO planeigenaar (id, naam, code) VALUES (442, 'Eemsmond', '1651');
INSERT INTO planeigenaar (id, naam, code) VALUES (443, 'Gemert-Bakel', '1652');
INSERT INTO planeigenaar (id, naam, code) VALUES (444, 'Halderberge', '1655');
INSERT INTO planeigenaar (id, naam, code) VALUES (445, 'Heeze-Leende', '1658');
INSERT INTO planeigenaar (id, naam, code) VALUES (446, 'Laarbeek', '1659');
INSERT INTO planeigenaar (id, naam, code) VALUES (447, 'Reiderland', '1661');
INSERT INTO planeigenaar (id, naam, code) VALUES (448, 'De Marne', '1663');
INSERT INTO planeigenaar (id, naam, code) VALUES (449, 'Zevenhuizen-Moerkapelle', '1666');
INSERT INTO planeigenaar (id, naam, code) VALUES (450, 'Reusel-De Mierden', '1667');
INSERT INTO planeigenaar (id, naam, code) VALUES (451, 'Roerdalen', '1669');
INSERT INTO planeigenaar (id, naam, code) VALUES (452, 'Maasdonk', '1671');
INSERT INTO planeigenaar (id, naam, code) VALUES (453, 'Rijnwoude', '1672');
INSERT INTO planeigenaar (id, naam, code) VALUES (454, 'Roosendaal', '1674');
INSERT INTO planeigenaar (id, naam, code) VALUES (455, 'Schouwen-Duiveland', '1676');
INSERT INTO planeigenaar (id, naam, code) VALUES (456, 'Aa en Hunze', '1680');
INSERT INTO planeigenaar (id, naam, code) VALUES (457, 'Borger-Odoorn', '1681');
INSERT INTO planeigenaar (id, naam, code) VALUES (458, 'Cuijk', '1684');
INSERT INTO planeigenaar (id, naam, code) VALUES (459, 'Landerd', '1685');
INSERT INTO planeigenaar (id, naam, code) VALUES (460, 'De Wolden', '1690');
INSERT INTO planeigenaar (id, naam, code) VALUES (461, 'Noord-Beveland', '1695');
INSERT INTO planeigenaar (id, naam, code) VALUES (462, 'Wijdemeren', '1696');
INSERT INTO planeigenaar (id, naam, code) VALUES (463, 'Noordenveld', '1699');
INSERT INTO planeigenaar (id, naam, code) VALUES (464, 'Twenterand', '1700');
INSERT INTO planeigenaar (id, naam, code) VALUES (465, 'Westerveld', '1701');
INSERT INTO planeigenaar (id, naam, code) VALUES (466, 'Sint Anthonis', '1702');
INSERT INTO planeigenaar (id, naam, code) VALUES (467, 'Lingewaard', '1705');
INSERT INTO planeigenaar (id, naam, code) VALUES (468, 'Cranendonck', '1706');
INSERT INTO planeigenaar (id, naam, code) VALUES (469, 'Steenwijkerland', '1708');
INSERT INTO planeigenaar (id, naam, code) VALUES (470, 'Moerdijk', '1709');
INSERT INTO planeigenaar (id, naam, code) VALUES (471, 'Echt-Susteren', '1711');
INSERT INTO planeigenaar (id, naam, code) VALUES (472, 'Sluis', '1714');
INSERT INTO planeigenaar (id, naam, code) VALUES (473, 'Drimmelen', '1719');
INSERT INTO planeigenaar (id, naam, code) VALUES (474, 'Bernheze', '1721');
INSERT INTO planeigenaar (id, naam, code) VALUES (475, 'Ferwerderadiel', '1722');
INSERT INTO planeigenaar (id, naam, code) VALUES (476, 'Alphen-Chaam', '1723');
INSERT INTO planeigenaar (id, naam, code) VALUES (477, 'Bergeijk', '1724');
INSERT INTO planeigenaar (id, naam, code) VALUES (478, 'Bladel', '1728');
INSERT INTO planeigenaar (id, naam, code) VALUES (479, 'Gulpen-Wittem', '1729');
INSERT INTO planeigenaar (id, naam, code) VALUES (480, 'Tynaarlo', '1730');
INSERT INTO planeigenaar (id, naam, code) VALUES (481, 'Midden-Drenthe', '1731');
INSERT INTO planeigenaar (id, naam, code) VALUES (482, 'Overbetuwe', '1734');
INSERT INTO planeigenaar (id, naam, code) VALUES (483, 'Hof van Twente', '1735');
INSERT INTO planeigenaar (id, naam, code) VALUES (484, 'Neder-Betuwe', '1740');
INSERT INTO planeigenaar (id, naam, code) VALUES (485, 'Rijssen-Holten', '1742');
INSERT INTO planeigenaar (id, naam, code) VALUES (486, 'Geldrop-Mierlo', '1771');
INSERT INTO planeigenaar (id, naam, code) VALUES (487, 'Olst-Wijhe', '1773');
INSERT INTO planeigenaar (id, naam, code) VALUES (488, 'Dinkelland', '1774');
INSERT INTO planeigenaar (id, naam, code) VALUES (489, 'Westland', '1783');
INSERT INTO planeigenaar (id, naam, code) VALUES (490, 'Midden-Delfland', '1842');
INSERT INTO planeigenaar (id, naam, code) VALUES (491, 'Berkelland', '1859');
INSERT INTO planeigenaar (id, naam, code) VALUES (492, 'Bronckhorst', '1876');
INSERT INTO planeigenaar (id, naam, code) VALUES (493, 'Sittard-Geleen', '1883');
INSERT INTO planeigenaar (id, naam, code) VALUES (494, 'Zwartewaterland', '1896');
INSERT INTO planeigenaar (id, naam, code) VALUES (495, 'Leidschendam-Voorburg', '1916');
INSERT INTO planeigenaar (id, naam, code) VALUES (496, 'Pijnacker-Nootdorp', '1926');
INSERT INTO planeigenaar (id, naam, code) VALUES (497, 'Montferland', '1955');
INSERT INTO planeigenaar (id, naam, code) VALUES (498, 'Menterwolde', '1987');

ALTER TABLE ONLY planeigenaar ADD CONSTRAINT planeigenaar_pkey PRIMARY KEY (id);