INSERT
INTO
    GISVIEWER_PLIM35.APPLICATIE
    (       
        ID,
        NAAM,
        CODE,
        GEBRUIKERS_CODE,
        PARENT,
        DATUM_GEBRUIKT,
        READ_ONLY,
        USER_COPY,
        VERSIE,
        DEFAULT_APP
    )
    SELECT APPLICATIE_ID_SEQ.nextval,SETTING, SETTING, '', 0, '2011-09-21',1,0,1,0
    FROM (SELECT SETTING FROM CONFIGURATIE GROUP BY SETTING);

-- Insert gebruikers_codes in applicatie.
    
update GISVIEWER_PLIM35.APPLICATIE a
set a.GEBRUIKERS_CODE=
(SELECT u.PERSONALURL FROM KAARTENBALIE_PLIM35.USERS u, KAARTENBALIE_PLIM35.USERS_ROLES ur, KAARTENBALIE_PLIM35.ROLES r
where u.ID = ur.USERS AND r.ID = ur.ROLE AND r.ROLE = a.CODE AND rownum = 1);

-- Set instellingen van kaartlagen in applicatie.
INSERT INTO GISVIEWER_PLIM35.USER_KAARTLAAG(ID,CODE,THEMAID,DEFAULT_ON)
SELECT GISVIEWER_PLIM35.USER_KAARTLAAG_ID_SEQ.nextval, CODE,ID,VISIBLE
FROM
(SELECT a.CODE, t.ID , t.VISIBLE
FROM GISVIEWER_PLIM35.APPLICATIE a,GISVIEWER_PLIM35.THEMAS t, KAARTENBALIE_PLIM35.ORGANIZATION_LAYERS ol, KAARTENBALIE_PLIM35.USERS u, KAARTENBALIE_PLIM35.LAYER l, KAARTENBALIE_PLIM35.SERVICE_PROVIDER s
WHERE u.MAIN_ORGANIZATION = ol.ORGANIZATION AND ol.LAYER = l.ID AND t.WMS_LAYERS_REAL = s.ABBR || '_' || l.NAME AND u.PERSONALURL = a.GEBRUIKERS_CODE);
