-- drops
BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE cms_pagina';
	EXECUTE IMMEDIATE 'DROP TABLE cms_menu_menuitem';
	EXECUTE IMMEDIATE 'DROP TABLE cms_menuitem';
	EXECUTE IMMEDIATE 'DROP TABLE cms_menu';
EXCEPTION
   	WHEN OTHERS THEN
   	IF SQLCODE != -942 THEN
   		RAISE;
   	END IF;
END;
